### ISSUE TITLE
cannot coerce class ‘"dist"’ to a data.frame

### ISSUE THREAD

**Issue by leiallen521** [rpatin/segtools#2]
Hi Patin:
     I am following your vignettes: preparing data to learn the tools, the issue occurred like title when i run the covariate calculations parts, no matter to use your example data "simulmode" or my own data, the error cannot fix. I am trouble in this step now, do you know how to solve this problem, thanks.
![image](https://user-images.githubusercontent.com/81500134/146882211-027b8fec-9791-49a4-9335-387d96954dda.png)

**Comment by leiallen521** [comment]
> Hi Patin: I am following your vignettes: preparing data to learn the tools, the issue occurred like title when i run the covariate calculations parts, no matter to use your example data "simulmode" or my own data, the error cannot fix. I am trouble in this step now, do you know how to solve this problem, thanks. ![image](https://user-images.githubusercontent.com/81500134/146882211-027b8fec-9791-49a4-9335-387d96954dda.png)

btw, the error occurred in function: add_covariates ,  the code like below:
simple_data <- k[,c("timestamp","location.long","location.lat")]
all K<- add_covariates(simple_data,coord.names = c("location.long","location.lat"), timecol = "timestamp", smoothed = TRUE)

**Comment by rpatin** [comment]
Hi, 
A quick answer : I think this comes from a conflict with package "sf" that is loaded in your R session. If you unload the package with : 
detach("package:vegan", unload=TRUE)
The error should go aware. In case this does not solve your problem I will take a look at it in January.
Cheers,
Rémi

**Comment by leiallen521** [comment]
> Hi, A quick answer : I think this comes from a conflict with package "sf" that is loaded in your R session. If you unload the package with : detach("package:vegan", unload=TRUE) The error should go aware. In case this does not solve your problem I will take a look at it in January. Cheers, Rémi

**Comment by leiallen521** [comment]
> > Hi, A quick answer : I think this comes from a conflict with package "sf" that is loaded in your R session. If you unload the package with : detach("package:vegan", unload=TRUE) The error should go aware. In case this does not solve your problem I will take a look at it in January. Cheers, Rémi

Hi Rémi,
nich to see your reply. i have detach all the package and run it again, but the issue still can't fix.  Then i reinstall the segcluste2d package, it works well and fix it.   I think the issue may result from the failure I install GitHub version this morning, and the package damaged. 
Best wishes!
Yu Lei
